version: '3'

volumes:
  bundle:
  db:

services:
  db:
    image: nouchka/sqlite3:latest
    volumes:
      - db:/root/db
    stdin_open: true
    tty: true

  web: &rails
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails assets:precompile && bundle exec rails s --early-hints -b '0.0.0.0'"
    volumes:
      - .:/myapp
      - bundle:/usr/local/bundle
    tmpfs: /myapp/tmp
    depends_on:
      - db
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=production
      - RAILS_SERVE_STATIC_FILES=true
